idn:
    max_attemps: 2
    time_out: 2500
    regexp: "[1-9][0-9]{5,10}"
    field: cedula

sounds:
    enter_id: "custom/id-please-type"
    no_id: "custom/id-you-have-not-entered"
    id_invalid: "custom/id-invalid"
    try_again: "custom/id-try-again"

request:
    url: "http://bus.comedal.com.co:8022/ws/ivr/datos-cedula"
    method: "GET"
    params:
        cedula: "{cedula}"
    json:
        cedula: "{cedula}"
    auth: 
        login: null
        password: null
    timeout: 2

variables:
    ID_NUMBER: "{cedula}"
    CALLERID(name): "{nombre} - {cedula} - {sucursal} - {email}"
    AGE: "{age}"
    EXTRA1": "{estado}"
    EXTRA2": "{clasificacion}"
    EXTRA3": "{sucursal}"
    EXTRA4": "{email}"

status:
    variable: "ID_STATUS"
