version: "3.7"
services:
  fastagi:
    build: fastagi
    restart: always
    ports:
      - 4573:8080
    environment:
      GETIDDIR: /etc/getid
    volumes:
      - ./fastagi/src/:/app
      - ./config.yaml:/etc/config.yaml
      - /etc/localtime:/etc/localtime
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python server.py
